In [55]:
import pandas as pd
import json
from pandas.io.json import json_normalize
from geopy.geocoders import Nominatim

In [29]:
ny_json=json.load(open('newyork_data.json'))

In [30]:
ny_json=json_normalize(ny_json['features'])
ny_json['Borough']=ny_json['properties.borough']
ny_json['Neighborhood']=ny_json['properties.name']
ny_json['Latitude']=ny_json['geometry.coordinates'].apply(lambda x:x[0])
ny_json['Longitude']=ny_json['geometry.coordinates'].apply(lambda x:x[1])
ny_json=ny_json[['Borough','Neighborhood','Latitude','Longitude']]
ny_json

           Borough         Neighborhood   Latitude  Longitude
0            Bronx            Wakefield -73.847201  40.894705
1            Bronx           Co-op City -73.829939  40.874294
2            Bronx          Eastchester -73.827806  40.887556
3            Bronx            Fieldston -73.905643  40.895437
4            Bronx            Riverdale -73.912585  40.890834
5            Bronx          Kingsbridge -73.902818  40.881687
6        Manhattan          Marble Hill -73.910660  40.876551
7            Bronx             Woodlawn -73.867315  40.898273
8            Bronx              Norwood -73.879391  40.877224
9            Bronx       Williamsbridge -73.857446  40.881039
10           Bronx           Baychester -73.835798  40.866858
11           Bronx       Pelham Parkway -73.854756  40.857413
12           Bronx          City Island -73.786488  40.847247
13           Bronx         Bedford Park -73.885512  40.870185
14           Bronx   University Heights -73.910416  40.855727
15           Bronx       Morris Heights -73.919672  40.847898
16           Bronx              Fordham -73.896427  40.860997
17           Bronx         East Tremont -73.887356  40.842696
18           Bronx           West Farms -73.877745  40.839475
19           Bronx         High  Bridge -73.926102  40.836623
20           Bronx              Melrose -73.909422  40.819754
21           Bronx           Mott Haven -73.916100  40.806239
22           Bronx          Port Morris -73.913221  40.801664
23           Bronx             Longwood -73.895788  40.815099
24           Bronx          Hunts Point -73.883315  40.809730
25           Bronx           Morrisania -73.901506  40.823592
26           Bronx            Soundview -73.865746  40.821012
27           Bronx         Clason Point -73.854144  40.806551
28           Bronx          Throgs Neck -73.816350  40.815109
29           Bronx         Country Club -73.824099  40.844246
..             ...                  ...        ...        ...
276      Manhattan             Flatiron -73.990947  40.739673
277         Queens    Sunnyside Gardens -73.918193  40.745652
278         Queens           Blissville -73.932442  40.737251
279       Brooklyn         Fulton Ferry -73.995508  40.703281
280       Brooklyn         Vinegar Hill -73.981116  40.703321
281       Brooklyn           Weeksville -73.930531  40.675040
282       Brooklyn    Broadway Junction -73.903317  40.677861
283       Brooklyn                Dumbo -73.988753  40.703176
284  Staten Island        Manor Heights -74.120594  40.601810
285  Staten Island          Willowbrook -74.132084  40.603707
286  Staten Island         Sandy Ground -74.217766  40.541140
287  Staten Island          Egbertville -74.127272  40.579119
288         Queens              Roxbury -73.892138  40.567376
289       Brooklyn            Homecrest -73.959185  40.598525
290         Queens       Middle Village -73.881143  40.716415
291  Staten Island         Prince's Bay -74.201526  40.526264
292  Staten Island      Lighthouse Hill -74.137927  40.576506
293  Staten Island      Richmond Valley -74.229571  40.519541
294         Queens                Malba -73.826678  40.790602
295       Brooklyn        Highland Park -73.890346  40.681999
296       Brooklyn              Madison -73.948415  40.609378
297          Bronx            Bronxdale -73.861726  40.852723
298          Bronx             Allerton -73.859319  40.865788
299          Bronx  Kingsbridge Heights -73.901523  40.870392
300       Brooklyn              Erasmus -73.948177  40.646926
301      Manhattan         Hudson Yards -74.000111  40.756658
302         Queens              Hammels -73.805530  40.587338
303         Queens            Bayswater -73.765968  40.611322
304         Queens         Queensbridge -73.945631  40.756091
305  Staten Island            Fox Hills -74.081740  40.617311

[306 rows x 4 columns]

In [58]:
x=Nominatim(user_agent='Korba')
x.geocode('Korba')

GeocoderTimedOut: Service timed out

In [4]:
df1=df[df['Borough']=='Manhattan'].reset_index(drop=True)

In [5]:
def neighborhoodname(nta):
    return nta.split('-')[0]

In [6]:
df1['Neighborhood']=df1['NTA Name'].apply(neighborhoodname)

In [42]:
df1=df1[df1['Year']==2010]

In [44]:
df1

,Borough,Year,FIPS County Code,NTA Code,NTA Name,Population,Neighborhood
29,Manhattan,2010,61,MN01,Marble Hill-Inwood,46746,Marble Hill
30,Manhattan,2010,61,MN03,Central Harlem North-Polo Grounds,75282,Central Harlem North
31,Manhattan,2010,61,MN04,Hamilton Heights,48520,Hamilton Heights
32,Manhattan,2010,61,MN06,Manhattanville,22950,Manhattanville
33,Manhattan,2010,61,MN09,Morningside Heights,55929,Morningside Heights
34,Manhattan,2010,61,MN11,Central Harlem South,43383,Central Harlem South
35,Manhattan,2010,61,MN12,Upper West Side,132378,Upper West Side
36,Manhattan,2010,61,MN13,Hudson Yards-Chelsea-Flat Iron-Union Square,70150,Hudson Yards
37,Manhattan,2010,61,MN14,Lincoln Square,61489,Lincoln Square
38,Manhattan,2010,61,MN15,Clinton,45884,Clinton
39,Manhattan,2010,61,MN17,Midtown-Midtown South,28630,Midtown
40,Manhattan,2010,61,MN19,Turtle Bay-East Midtown,51231,Turtle Bay
41,Manhattan,2010,61,MN20,Murray Hill-Kips Bay,50742,Murray Hill
42,Manhattan,2010,61,MN21,Gramercy,27988,Gramercy
43,Manhattan,2010,61,MN22,East Village,44136,East Village
44,Manhattan,2010,61,MN23,West Village,66880,West Village
45,Manhattan,2010,61,MN24,SoHo-TriBeCa-Civic Center-Little Italy,42742,SoHo
46,Manhattan,2010,61,MN25,Battery Park City-Lower Manhattan,39699,Battery Park City
47,Manhattan,2010,61,MN27,Chinatown,47844,Chinatown
48,Manhattan,2010,61,MN28,Lower East Side,72957,Lower East Side
49,Manhattan,2010,61,MN31,Lenox Hill-Roosevelt Island,80771,Lenox Hill
50,Manhattan,2010,61,MN32,Yorkville,77942,Yorkville
51,Manhattan,2010,61,MN33,East Harlem South,57902,East Harlem South
52,Manhattan,2010,61,MN34,East Harlem North,58019,East Harlem North
53,Manhattan,2010,61,MN35,Washington Heights North,67136,Washington Heights North
54,Manhattan,2010,61,MN36,Washington Heights South,84438,Washington Heights South
55,Manhattan,2010,61,MN40,Upper East Side-Carnegie Hill,61207,Upper East Side
56,Manhattan,2010,61,MN50,Stuyvesant Town-Cooper Village,21049,Stuyvesant Town
57,Manhattan,2010,61,MN99,park-cemetery-etc-Manhattan,1849,park

In [34]:
ny_manhattan=ny_json[ny_json['Borough']=='Manhattan']

In [52]:
right=ny_manhattan.merge(df1,on='Neighborhood',how='right')
right[right['Borough_x'].isnull()]

,Borough_x,Neighborhood,Latitude,Longitude,Borough_y,Year,FIPS County Code,NTA Code,NTA Name,Population
21,NaN,Central Harlem North,NaN,NaN,Manhattan,2010,61,MN03,Central Harlem North-Polo Grounds,75282
22,NaN,Central Harlem South,NaN,NaN,Manhattan,2010,61,MN11,Central Harlem South,43383
23,NaN,SoHo,NaN,NaN,Manhattan,2010,61,MN24,SoHo-TriBeCa-Civic Center-Little Italy,42742
24,NaN,East Harlem South,NaN,NaN,Manhattan,2010,61,MN33,East Harlem South,57902
25,NaN,East Harlem North,NaN,NaN,Manhattan,2010,61,MN34,East Harlem North,58019
26,NaN,Washington Heights North,NaN,NaN,Manhattan,2010,61,MN35,Washington Heights North,67136
27,NaN,Washington Heights South,NaN,NaN,Manhattan,2010,61,MN36,Washington Heights South,84438
28,NaN,park,NaN,NaN,Manhattan,2010,61,MN99,park-cemetery-etc-Manhattan,1849

In [54]:
left=ny_manhattan.merge(df1,on='Neighborhood',how='left')
left[left['NTA Code'].isnull()]

,Borough_x,Neighborhood,Latitude,Longitude,Borough_y,Year,FIPS County Code,NTA Code,NTA Name,Population
2,Manhattan,Washington Heights,-73.936900,40.851903,NaN,NaN,NaN,NaN,NaN,NaN
3,Manhattan,Inwood,-73.921210,40.867684,NaN,NaN,NaN,NaN,NaN,NaN
6,Manhattan,Central Harlem,-73.943211,40.815976,NaN,NaN,NaN,NaN,NaN,NaN
7,Manhattan,East Harlem,-73.944182,40.792249,NaN,NaN,NaN,NaN,NaN,NaN
11,Manhattan,Roosevelt Island,-73.949168,40.762160,NaN,NaN,NaN,NaN,NaN,NaN
17,Manhattan,Chelsea,-74.003116,40.744035,NaN,NaN,NaN,NaN,NaN,NaN
18,Manhattan,Greenwich Village,-73.999914,40.726933,NaN,NaN,NaN,NaN,NaN,NaN
21,Manhattan,Tribeca,-74.010683,40.721522,NaN,NaN,NaN,NaN,NaN,NaN
22,Manhattan,Little Italy,-73.997305,40.719324,NaN,NaN,NaN,NaN,NaN,NaN
23,Manhattan,Soho,-74.000657,40.722184,NaN,NaN,NaN,NaN,NaN,NaN
25,Manhattan,Manhattan Valley,-73.964286,40.797307,NaN,NaN,NaN,NaN,NaN,NaN
29,Manhattan,Financial District,-74.010665,40.707107,NaN,NaN,NaN,NaN,NaN,NaN
30,Manhattan,Carnegie Hill,-73.953256,40.782683,NaN,NaN,NaN,NaN,NaN,NaN
31,Manhattan,Noho,-73.988434,40.723259,NaN,NaN,NaN,NaN,NaN,NaN
32,Manhattan,Civic Center,-74.005415,40.715229,NaN,NaN,NaN,NaN,NaN,NaN
33,Manhattan,Midtown South,-73.988713,40.748510,NaN,NaN,NaN,NaN,NaN,NaN
34,Manhattan,Sutton Place,-73.963556,40.760280,NaN,NaN,NaN,NaN,NaN,NaN
36,Manhattan,Tudor City,-73.971219,40.746917,NaN,NaN,NaN,NaN,NaN,NaN
38,Manhattan,Flatiron,-73.990947,40.739673,NaN,NaN,NaN,NaN,NaN,NaN